### PR TITLE
Add SCons to Build Systems

### PR DESCRIPTION
**Pull request by retrohacker**
Not sure on the description (it is definitely biased) but I pulled it from their homepage.

After working with several projects and build systems, SCons has been a breath of fresh air.

### CODE REVIEW

**Comment by sjfricke** [comment]
I see nothing wrong, as long as you explained what it roughly does before I click on it I think it looks good to me

**Comment by sjfricke** [comment]
@retrohacker I would change it and get rid of `SCons` in the description, otherwise its the a redundant use of it displaying

`SCons - SCons is ....`

and have

`SCons - Easier, more ....`

**Comment by aleksandar-todorovic** [comment]
Ping.

Any chances you could update your PR?

**Comment by retrohacker** [comment]
Sorry for the delay. This has been updated.

**Comment by sjfricke** [comment]
Thanks!

**Pull request merged**
