### PR TITLE
merge: embedded system tools

### PR DESCRIPTION
**Pull request by firecrypt**

### CODE REVIEW

**Comment by sjfricke** [comment]
@firecrypt Thanks for the addition of RTOS as I think that's a good section to have.

Few small things:

- Whats wrong with justing using `[[3-clause BSD][6]]`
- For the MIT License why not use [A global MIT page for future projects using it as well](https://en.wikipedia.org/wiki/MIT_License)
- For Atom text editor get rid of the prefix `A`
  - ` A hackable text` -> `Hackable text`

**Comment by firecrypt** [comment]
@sjfricke 

- Habit. The place I work at usually wants links directly to project licenses. MIT/BSD projects don't usually differ from the standard license, but GPL/LGPL can be all over the place with different types of exceptions. My standard practice is to just link directly against the project license. I can change them to the generic links if you like.
- Same as above.
- Will do.

**Comment by sjfricke** [comment]
@firecrypt I agree with the idea of linking to the project, I guess its more because the habit the repo is currently at.

Like the MIT license, if they don't have it exact then it should be linked with something like `Variation of MIT` but if its just the same MIT license its more of just having a redundant link.

I feel this should be a more defined addition to the contribution.md

if you want to keep the license as is right now I will come back to it if decide to change it

Thanks for bringing this good point up

**Comment by firecrypt** [comment]
@sjfricke I was actually going to propose a license review and update as an issue. I noticed that some other project license are incorrect (example: jansson is MIT, not Expat). I'll open an issue a get feedback before doing a bunch of changes.

**Comment by firecrypt** [comment]
Fixed links, should be ready for merge.

**Comment by sjfricke** [comment]
Thanks again for both the contribution of awesome C projects and the refactoring idea brought up for licenses

**Comment by firecrypt** [comment]
No problem!

**Pull request merged**
