### PR TITLE
add libvldmail

### PR DESCRIPTION
**Pull request by dertuxmalwieder**
I did a thing. Here's an entry for the list.

### CODE REVIEW

**Comment by sjfricke** [comment]
@dertuxmalwieder thanks for adding your mail validator! I will have time to personally look more closely into it by end of the week. I assume its all good from the quick glance I gave, but it being such a new 1 day repo, want to just double check.

**Comment by dertuxmalwieder** [comment]
Thank you! I will maintain it as long as I can to fulfill your requirements. :-)

**Comment by sjfricke** [comment]
Lgtm. Thanks  again for contributions

**Comment by dertuxmalwieder** [comment]
Thank you for merging :)

**Pull request merged**
