### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abhi18av**
Added VsCode as a modern C editor

### CODE REVIEW

**Comment by aleksandar-todorovic** [comment]
We should probably use the official name of the program, which is, in this case, "Visual Studio Code", not "VsCode".

**Comment by aleksandar-todorovic** [comment]
Closing for the lack of response, Visual Studio will be added in a separate commit.

**Comment by abhi18av** [comment]
Whoops! @aleksandar-todorovic I totally forgot about this PR :)

**Comment by aleksandar-todorovic** [comment]
Feel free to create a new one or let me know if you're planning on fixing this one. :)

**Comment by abhi18av** [comment]
Yup, it's here => https://github.com/aleksandar-todorovic/awesome-c/pull/52

**Pull request closed without merging**
